### ISSUE TITLE
Batogram wont start

### ISSUE THREAD

**Issue by jokot025** [jmears63/batogram#6]
I installed batogram as per the instructions and when I try to launch the GUI with the ```batogram``` command I get the following error:  ``` OverflowError: Python integer 57007 out of bounds for int16``` for this line of code ```stegangraphy.py", line 11, in LSBSteganography
    prefix_value: np.int16 = np.int16(0xDEAF)```.

I am on linux mint 22, Python 3.12.3.

**Comment by jmears63** [comment]
Interesting, I haven't encountered that. So it is literally during the
startup of the program? Not when loading a wav file?

Does a traceback get printed to the terminal that you launched batogram
from? Could you copy any output appearing in the terminal window to me?
That should give me an idea which part of the code this happened
in.

**Comment by jmears63** [comment]
OK I see your update with the detail about np.int16 in steganography.py. I suspect we are using different versions of numpy, and yours is pickier than mine. I have just committed a small change which I am guessing will make this problem go away. So, get the latest code from github and let me know how you get on.

**Comment by jokot025** [comment]
Hi!

Sorry for replying so late, yes the error pops up when starting the program
and yes there is a traceback and I woll copy it for you tommorrow, sorry I
didn't do it earlier.

Best regards,
Jovan

**Comment by jmears63** [comment]
See my previous comment, I checked in a possible fix yesterday.

**Comment by jokot025** [comment]
Apologies, I only saw one response in my email. Yep that fixed it, works fine now, thanks!
